### ISSUE TITLE
How to move the cursor right?

### ISSUE THREAD

**Issue by hong0980** [fidian/ansi#26]
How to move the cursor to the right in Ubuntu 20.04.3 LTS in Actions on github? Just like echo -en "\033[70G[ ", export ANSI_FORCE_SUPPORT=anything has been added, ansi --color-table
ansi --color-codes can run normally, thank you!

**Comment by fidian** [comment]
`ansi --forward` or `ansi --forward=1` both move the cursor to the right by one column. It uses `echo -en "\033[1C" to move and does not write a space to the screen. I believe that your escape sequence moves to column 70 and then writes "[ ".

As for how to do it in Actions on GitHub, I'm not entirely sure because I don't know the environment well. If it is just the same as a Linux/Unix terminal, then `ansi --forward` could work.

**Comment by hong0980** [comment]
thank you for your reply! I use the state display
`status() {
   local CHECK=$?
   echo -en "\\033[70G[ "
   if [$CHECK = 0 ]; then
     echo -en "\\033[1;33mOK"
   else
     echo -en "\\033[1;31mFailed"
   fi
   echo -e "\\033[0;39m ]"
}`
It can be used in general terminals, but it won’t move in the GitHub Actions environment. I don’t know why? It may be a missing component. Thanks!

**Comment by fidian** [comment]
I don't see `ansi` used in there, nor do I see `CSI [ n C` code to move right.

Not all terminals support all ANSI commands. Also, it depends on how you are viewing this - if you aren't looking at a terminal, then you need to have that ANSI code supported by the file viewer. My guess is that `CSI [ n G` is not supported by GitHub's viewer for the log of the action.

You might be able to use `echo -en "\r\033[70C"` to position to column 70. Another option is to measure the length of the string that has already been written and write out the number of spaces to equal 70. A third option is to use `ansi --report-position` but that command is really, really hard to use.

Because this does not really affect `ansi` and is a question about ANSI escape sequences and how GitHub Action log viewer supports them, I believe this is out of scope for `ansi`.
